### PR TITLE
COVESA VSS mapping over IEEE 1722.

### PR DESCRIPTION
**Pull request by nayakned**
Creating a PR for discussing a COVESA VSS mapping over IEEE 1722.

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Added initial spec document. "Readable"/rendered version: https://github.com/boschglobal/Open1722/blob/feat/custom/vss/examples/acf-vss/protocol_description/acf-vss.md

**Comment by adriaan-niess** [comment]
I've noticed the timestamp field was 32 bit instead of in text 64, so I pushed a small update. The diagrams have been correct.

**Comment by SebastianSchildt** [comment]
@nayakned this needs some rebasing

**Comment by nayakned** [comment]
> @nayakned this needs some rebasing

I have setup a new PR (#44) rebased on the current main branch.

**Pull request closed without merging**
